version: 2

updates:

  - package-ecosystem: "gomod"
    directory: "/always"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/graceful"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/memkv"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/probe"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
