name: check-probe

on:
  push:
    branches:
      - "main"
    paths:
      - "probe/**"
      - ".github/workflows/probe.yml"
  pull_request:
    branches:
      - "*"
    paths:
      - "probe/**"
      - ".github/workflows/probe.yml"

jobs:

  clean:
    name: clean
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        go: [stable]
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run go mod tidy
        working-directory: probe
        run: go mod tidy && git diff --exit-code
      - name: Run go mod verify
        working-directory: probe
        run: go mod verify
      - name: Run formatting
        working-directory: probe
        run: go run golang.org/x/tools/cmd/goimports@latest -w . && git diff --exit-code

  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      matrix:
        go: [stable]
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run go linting
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=4m
          working-directory: probe

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        go: [stable]
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run tests
        working-directory: probe
        run: go test -shuffle=on -v -count=1 -race -failfast -timeout=30s -covermode=atomic -coverprofile=coverage.out ./...
      - name: Codecov Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: probe

  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        go: [stable]
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run benchmarks
        working-directory: probe
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x -timeout=10s ./...

  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      matrix:
        go: [stable]
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run go generate
        working-directory: probe
        run: go generate ./... && git diff --exit-code
      - name: Run go build
        working-directory: probe
        run: go build -o /dev/null ./...
